[package]
name = "zf"
version = "0.1.0"
authors = ["KiÃ«d Llaentenn <kiedtl@tilde.team>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
